interface _RbsRailsPathHelpers
  def rails_mailers_path: (*untyped) -> String
  def rails_info_properties_path: (*untyped) -> String
  def rails_info_routes_path: (*untyped) -> String
  def rails_info_path: (*untyped) -> String
  def graphql_path: (*untyped) -> String
  def actors_path: (*untyped) -> String
  def actor_path: (*untyped) -> String
  def countries_path: (*untyped) -> String
  def country_path: (*untyped) -> String
  def movies_path: (*untyped) -> String
  def movie_path: (*untyped) -> String
  def roles_path: (*untyped) -> String
  def role_path: (*untyped) -> String
  def rails_postmark_inbound_emails_path: (*untyped) -> String
  def rails_relay_inbound_emails_path: (*untyped) -> String
  def rails_sendgrid_inbound_emails_path: (*untyped) -> String
  def rails_mandrill_inbound_health_check_path: (*untyped) -> String
  def rails_mandrill_inbound_emails_path: (*untyped) -> String
  def rails_mailgun_inbound_emails_path: (*untyped) -> String
  def rails_conductor_inbound_emails_path: (*untyped) -> String
  def rails_conductor_inbound_email_path: (*untyped) -> String
  def new_rails_conductor_inbound_email_source_path: (*untyped) -> String
  def rails_conductor_inbound_email_sources_path: (*untyped) -> String
  def rails_conductor_inbound_email_reroute_path: (*untyped) -> String
  def rails_conductor_inbound_email_incinerate_path: (*untyped) -> String
  def rails_service_blob_path: (*untyped) -> String
  def rails_service_blob_proxy_path: (*untyped) -> String
  def rails_blob_representation_path: (*untyped) -> String
  def rails_blob_representation_proxy_path: (*untyped) -> String
  def rails_disk_service_path: (*untyped) -> String
  def update_rails_disk_service_path: (*untyped) -> String
  def rails_direct_uploads_path: (*untyped) -> String
  def rails_representation_path: (*untyped) -> String
  def rails_blob_path: (*untyped) -> String
  def rails_storage_proxy_path: (*untyped) -> String
  def rails_storage_redirect_path: (*untyped) -> String
  def rails_mailers_url: (*untyped) -> String
  def rails_info_properties_url: (*untyped) -> String
  def rails_info_routes_url: (*untyped) -> String
  def rails_info_url: (*untyped) -> String
  def graphql_url: (*untyped) -> String
  def actors_url: (*untyped) -> String
  def actor_url: (*untyped) -> String
  def countries_url: (*untyped) -> String
  def country_url: (*untyped) -> String
  def movies_url: (*untyped) -> String
  def movie_url: (*untyped) -> String
  def roles_url: (*untyped) -> String
  def role_url: (*untyped) -> String
  def rails_postmark_inbound_emails_url: (*untyped) -> String
  def rails_relay_inbound_emails_url: (*untyped) -> String
  def rails_sendgrid_inbound_emails_url: (*untyped) -> String
  def rails_mandrill_inbound_health_check_url: (*untyped) -> String
  def rails_mandrill_inbound_emails_url: (*untyped) -> String
  def rails_mailgun_inbound_emails_url: (*untyped) -> String
  def rails_conductor_inbound_emails_url: (*untyped) -> String
  def rails_conductor_inbound_email_url: (*untyped) -> String
  def new_rails_conductor_inbound_email_source_url: (*untyped) -> String
  def rails_conductor_inbound_email_sources_url: (*untyped) -> String
  def rails_conductor_inbound_email_reroute_url: (*untyped) -> String
  def rails_conductor_inbound_email_incinerate_url: (*untyped) -> String
  def rails_service_blob_url: (*untyped) -> String
  def rails_service_blob_proxy_url: (*untyped) -> String
  def rails_blob_representation_url: (*untyped) -> String
  def rails_blob_representation_proxy_url: (*untyped) -> String
  def rails_disk_service_url: (*untyped) -> String
  def update_rails_disk_service_url: (*untyped) -> String
  def rails_direct_uploads_url: (*untyped) -> String
  def rails_representation_url: (*untyped) -> String
  def rails_blob_url: (*untyped) -> String
  def rails_storage_proxy_url: (*untyped) -> String
  def rails_storage_redirect_url: (*untyped) -> String
end
